# Generated by Django 4.2 on 2023-04-10 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('categoty', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_C',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User_E',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MainApp.user_c')),
                ('first_name', models.TextField(max_length=50)),
                ('second_name', models.TextField(max_length=50)),
                ('last_name', models.TextField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('phone', models.TextField(max_length=20)),
                ('about', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MainApp.user_e')),
                ('first_name', models.TextField(max_length=50)),
                ('second_name', models.TextField(max_length=50)),
                ('last_name', models.TextField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('phone', models.TextField(max_length=20)),
                ('about', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('about', models.TextField(max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.categories')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Total_Trade',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('about', models.TextField(max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.categories')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.client')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.executor')),
            ],
        ),
        migrations.CreateModel(
            name='E_Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.trade')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.executor')),
            ],
        ),
        migrations.CreateModel(
            name='E_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.categories')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.executor')),
            ],
        ),
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.executor')),
            ],
        ),
    ]
