# Generated by Django 4.2 on 2023-04-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_alter_client_id_alter_executor_id_delete_user_c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='about',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='executor',
            name='about',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='executor',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
