# Generated by Django 4.2 on 2023-04-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_client_about_alter_client_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='about',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='executor',
            name='about',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='executor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
